name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'  # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
    
    - name: Set Environment Variables
      run: |
        az webapp config appsettings set \
          --name your-app-name \
          --resource-group your-resource-group \
          --settings \
          MONGO_URI="${{ secrets.MONGO_URI }}" \
          DATABASE_NAME="${{ secrets.DATABASE_NAME }}"
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }} 